name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        file_path: .github/workflows/test_values.yaml
        key_paths: a.b.c.tag,d.e.f.tag
        set_value: hello world
